apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: development
  name: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: development
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: development
    spec:
      containers:
      - image: docker.io/httpd
        name: development
        resources: {}
status: {}
